name:                phony-sqlite-engine
version:             0.1.0.0
github:              "jorpic/phony-sqlite-engine"
license:             BSD3
author:              "Max Taldykin"
maintainer:          "jorpic@gmail.com"
copyright:           "2022 Max Taldykin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jorpic/phony-sqlite-engine#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - ImportQualifiedPost
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - NamedFieldPuns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - lens
  - containers
  - transformers
  - vector

executables:
  phony-sqlite-engine:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - phony-sqlite-engine

tests:
  phony-sqlite-engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - phony-sqlite-engine
    - hspec
    - containers
    - vector
